# Generated by Django 5.2.8 on 2026-02-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crear_cuenta_tutor',
            name='habilidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crear_cuenta_tutor',
            name='titulo_profesional',
            field=models.CharField(max_length=150),
        ),
    ]
