# Generated by Django 5.2.8 on 2026-02-08 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_crear_cuenta_tutor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crear_cuenta_tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
