# Generated by Django 5.2.8 on 2026-02-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_crear_cuenta_tutor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crear_cuenta_tutor',
            name='role',
        ),
        migrations.AddField(
            model_name='crear_cuenta_tutor',
            name='tipo',
            field=models.CharField(default='ofrece', editable=False, max_length=10),
        ),
    ]
