# Generated by Django 6.0.1 on 2026-02-08 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_crear_cuenta_tutor_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crear_cuenta_estudiante',
            name='role',
        ),
        migrations.AddField(
            model_name='crear_cuenta_estudiante',
            name='tipo',
            field=models.CharField(default='busca', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='crear_cuenta_estudiante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
