# Generated by Django 5.2.8 on 2026-02-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_crear_cuenta_estudiante_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crear_cuenta_tutor',
            name='dia_disponibles',
        ),
        migrations.RemoveField(
            model_name='crear_cuenta_tutor',
            name='habilidad',
        ),
        migrations.RemoveField(
            model_name='crear_cuenta_tutor',
            name='nivel_experiencia',
        ),
        migrations.CreateModel(
            name='TutorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=100)),
                ('nivel_experiencia', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')])),
                ('dia_disponible', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.crear_cuenta_tutor')),
            ],
        ),
    ]
