# Generated by Django 5.2.8 on 2026-02-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_crear_cuenta_estudiante_dia_disponibles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillmatch',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='skillmatch',
            name='fecha_match',
        ),
        migrations.AddField(
            model_name='skillmatch',
            name='skills_tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill_tutor', to='users.tutorskill'),
            preserve_default=False,
        ),
    ]
