# Generated by Django 5.2.8 on 2026-02-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_skillmatch_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillmatch',
            name='aprendiz',
        ),
        migrations.AddField(
            model_name='skillmatch',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_matches', to='users.crear_cuenta_estudiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillmatch',
            name='estudiante_skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_skill', to='users.estudianteskill'),
            preserve_default=False,
        ),
    ]
