# Generated by Django 6.0.1 on 2026-02-09 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_skillmatch_aprendiz_skillmatch_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversacion', to='users.skillmatch')),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.conversacion')),
                ('enviados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
