# Generated by Django 5.2.8 on 2026-02-09 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_conversacion_mensajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringsession',
            name='aprendiz',
        ),
        migrations.RemoveField(
            model_name='tutoringsession',
            name='tutor',
        ),
        migrations.AddField(
            model_name='tutoringsession',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutorias', to='users.skillmatch'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia'), ('pago_movil', 'Pago Móvil'), ('efectivo', 'Efectivo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('reembolsado', 'Reembolsado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='users.crear_cuenta_estudiante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recibidos', to='users.crear_cuenta_tutor')),
                ('tutoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='users.tutoringsession')),
            ],
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('procesado', 'Procesado')], max_length=20)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reembolso', to='users.pago')),
            ],
        ),
    ]
