# Generated by Django 5.2.8 on 2026-02-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_tutoringsession_aprendiz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='referencia',
            new_name='descripcion',
        ),
    ]
