# Generated by Django 5.2.8 on 2026-02-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_referencia_pago_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringsession',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorias', to='users.skillmatch'),
        ),
    ]
