# Generated by Django 5.2.8 on 2026-02-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_reembolso_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tutor',
        ),
    ]
