# Generated by Django 5.2.8 on 2026-02-09 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_pago_estudiante_remove_pago_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='session',
            new_name='tutoria',
        ),
        migrations.AddField(
            model_name='review',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.crear_cuenta_estudiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.crear_cuenta_tutor'),
            preserve_default=False,
        ),
    ]
