# Generated by Django 5.2.8 on 2026-02-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_session_review_tutoria_review_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='calificacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy Malo'), (2, 'Malo'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='comentario',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
