# Generated by Django 5.2.8 on 2026-02-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_review_calificacion_alter_review_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='calificacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy Malo'), (2, 'Malo'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
